### ISSUE TITLE
动态添加无效

### ISSUE THREAD

**Issue by EarthMass** [HaoXianSen/HYHSuspensionList#1]
动态添加无效，有问题

**Comment by EarthMass** [comment]
没有重新加载的操作，类似tableView reload

**Comment by HaoXianSen** [comment]
重新加载已经暴露除了内部属性innerTableView 你可以用这个去reload视图，但是主框架的reload我觉得没什么用，至于item项是外部传入的，你可以控制item的刷新

**Comment by HaoXianSen** [comment]
> 动态添加无效，有问题
可以简单的描述一下你的动态加载的场景吗？

**Comment by EarthMass** [comment]
方法里面重新添加项
- (id<HYHItemProtocol>)suspensionView:(nonnull HYHSuspensionView *)suspensionView itemAtSlideIndex:(NSInteger)index
内部会判断 itemsArr 是否为count = 0，= 0才会去添加，视图，如果要做到动态添加 项。就不能做到

[innerTableView reloadData]， itemAtSlideIndex 刷新也不会调用这个方法。

**Comment by EarthMass** [comment]
我的使用场景是，动态不增加，减少 suspensionView item,现在无法达到这个效果。

**Comment by EarthMass** [comment]
我现在暂时只能通过，重新创建 ZXSuspensionView去达到我的目的

**Comment by HaoXianSen** [comment]
哦，我明白你说的问题，你需要动态的更新item的数量，我找时间优化中加上这个功能。感谢！

**Comment by EarthMass** [comment]
我靠，作者你居然刚好在

**Comment by EarthMass** [comment]
这个库，写的很好，对于懒癌患者，使用起来可能有点繁琐，针对子视图的调用，封装上面可以优化一下，使用起来很乱。非常感谢，提供这么棒的库

**Comment by HaoXianSen** [comment]
好的，谢谢你提供的宝贵意见，我会在之后的时间里做一下这方面的优化 @EarthMass
